In [327]:
import numpy as np
from scipy.ndimage import label, generate_binary_structure
import scipy.ndimage as ndimage

In [4]:
input = """467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598.."""

In [145]:
data = np.array([ [c for c in l] for l in input.splitlines()])

In [223]:
for row in data:
    print(row)
    numbers = np.where(np.char.isnumeric(row))[0]
    symbols = np.where(~np.char.isnumeric(row) & (row != '.'))[0]
    #print(np.pad(row!='.',1))
    #print('--')

['4' '6' '7' '.' '.' '1' '1' '4' '.' '.']
['.' '.' '.' '*' '.' '.' '.' '.' '.' '.']
['.' '.' '3' '5' '.' '.' '6' '3' '3' '.']
['.' '.' '.' '.' '.' '.' '#' '.' '.' '.']
['6' '1' '7' '*' '.' '.' '.' '.' '.' '.']
['.' '.' '.' '.' '.' '+' '.' '5' '8' '.']
['.' '.' '5' '9' '2' '.' '.' '.' '.' '.']
['.' '.' '.' '.' '.' '.' '7' '5' '5' '.']
['.' '.' '.' '$' '.' '*' '.' '.' '.' '.']
['.' '6' '6' '4' '.' '5' '9' '8' '.' '.']


In [281]:
def groups(row):
    nrow = np.r_[0, np.char.isnumeric(row), 0]
    gr = np.flatnonzero(np.diff(nrow) != 0).reshape(-1,2)
    return [ np.arange(*r) for r in gr ]

def extract(row, group):
    return ''.join(row[group])
    #return ''.join(row[group[0]:group[1]])

In [308]:
for row in data:
    print(row)
    #numbers = np.where(np.char.isnumeric(row))[0]     
    for eg in groups(row):
        #print(row[eg])
        #print(np.where(row == eg, 1, 0))
        print(np.repeat(eg.T, repeats=1, axis=0))
        #print(extract(row, eg))
    #for eg in groups(row):
    #    print(np.arange(*eg))
        #print(np.where(np.array(range(*eg))), 1, 0)
    #    print(range(*eg))
    #    print(extract(row, eg))
    #symbols = np.where(~np.char.isnumeric(row) & (row != '.'))
    smask = np.where(~np.char.isnumeric(row) & (row != '.'), 1, 0)
    #print(smask)
    #print(np.where(smask, row, 0))
    print('-')
    #print(symbols[0])
    #print(np.pad(row!='.',1))

['4' '6' '7' '.' '.' '1' '1' '4' '.' '.']
[0 1 2]
[5 6 7]
-
['.' '.' '.' '*' '.' '.' '.' '.' '.' '.']
-
['.' '.' '3' '5' '.' '.' '6' '3' '3' '.']
[2 3]
[6 7 8]
-
['.' '.' '.' '.' '.' '.' '#' '.' '.' '.']
-
['6' '1' '7' '*' '.' '.' '.' '.' '.' '.']
[0 1 2]
-
['.' '.' '.' '.' '.' '+' '.' '5' '8' '.']
[7 8]
-
['.' '.' '5' '9' '2' '.' '.' '.' '.' '.']
[2 3 4]
-
['.' '.' '.' '.' '.' '.' '7' '5' '5' '.']
[6 7 8]
-
['.' '.' '.' '$' '.' '*' '.' '.' '.' '.']
-
['.' '6' '6' '4' '.' '5' '9' '8' '.' '.']
[1 2 3]
[5 6 7]
-


In [217]:
feats = np.where(~np.char.isnumeric(data) & (data != '.'), 1, 0)
#label(x)
feats

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [218]:
nums = np.where(np.char.isnumeric(data), 1, 0)
nums

array([[1, 1, 1, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 1, 1, 1, 0, 0]])

In [368]:
nstructure = [[0,0,0],
 [1,1,1],
 [0,0,0]]
labeled_arr, nlabels = label(nums, structure=nstructure)
labeled_arr

array([[ 1,  1,  1,  0,  0,  2,  2,  2,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  3,  0,  0,  4,  4,  4,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 5,  5,  5,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  6,  6,  0],
       [ 0,  0,  7,  7,  7,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  8,  8,  8,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  9,  9,  9,  0, 10, 10, 10,  0,  0]], dtype=int32)

In [372]:
for i in range(0, nlabels+1):
    n = np.where(labeled_arr == i, 1, 0) + feats
    masked_arr, _ = label(n, structure=generate_binary_structure(2,2))
    sizes = ndimage.sum(n, masked_arr , np.arange(0,50)) 
    mask = sizes > 1
    res = mask[masked_arr.ravel()].reshape(masked_arr.shape).astype(int)
    print(res.sum() > np.where(labeled_arr == i, 1, 0).sum())

False
True
False
True
True
True
False
True
True
True
True


In [320]:
n = np.where(labeled_arr == 1, 1, 0) + feats
n

array([[1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [355]:
labeled_array, _ = label(n, structure=generate_binary_structure(2,2))
sizes = ndimage.sum(n, labeled_array , np.arange(0,50)) 
mask = sizes > 1
mask[labeled_array.ravel()].reshape(labeled_array.shape).astype(int)

array([[1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [314]:
for i in range(1, nlabels+1):
    x = np.where(labeled_arr == i)
    print(x)

(array([0, 0, 0]), array([0, 1, 2]))
(array([0, 0, 0]), array([5, 6, 7]))
(array([2, 2]), array([2, 3]))
(array([2, 2, 2]), array([6, 7, 8]))
(array([4, 4, 4]), array([0, 1, 2]))
(array([5, 5]), array([7, 8]))
(array([6, 6, 6]), array([2, 3, 4]))
(array([7, 7, 7]), array([6, 7, 8]))
(array([9, 9, 9]), array([1, 2, 3]))
(array([9, 9, 9]), array([5, 6, 7]))


In [164]:
row[~np.array([0,1,2,3,4,5,6,7,8,9])]

array(['.', '.', '8', '9', '5', '.', '4', '6', '6', '.'], dtype='<U1')

In [170]:
np.where((row != '.'), 1, 0)

array([0, 1, 1, 1, 0, 1, 1, 1, 0, 0])

In [ ]:
np.where(np.char.isnumeric(row))

In [134]:
a = np.array([0, 1, 0, 1, 0, 0, 0, 1], dtype='bool')
b = np.array([1,1,0], dtype='bool')
idx = np.where(a)[0]

In [135]:
a

array([False,  True, False,  True, False, False, False,  True])

In [136]:
b

array([ True,  True, False])

In [137]:
idx

array([1, 3, 7])

In [138]:
a[idx[~b]] = False

IndexError: boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 8

In [131]:
a

array([False,  True, False,  True, False, False, False, False])