In [1]:
data = open("day5.txt") do f
    read(f, String)
end
NaN

NaN

In [54]:
x1, x2, x3, x4 = Int.(collect(Iterators.flatten(((1, 2), (3, 4)))))

4-element Vector{Int64}:
 1
 2
 3
 4

In [117]:
get!(m, 0, 1)

1

In [127]:
m = zeros(1000, 1000)

1000×1000 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0

In [154]:
m = zeros(1000, 1000)
for (x1, y1, x2, y2) = [ parse.(Int64, match(r"(\d+),(\d+) -> (\d+),(\d+)", x)) for x in split(data, '\n') ]
    x, y = x1, y1
    dx, dy = sign(x2-x1), sign(y2-y1)
    while x != x2 + dx || y != y2 + dy
        m[x,y] += 1
        x += dx
        y += dy
    end
end
length(m[m .> 1])

19472

In [85]:
x1, x2, x3, x4 = match(r"(\d+),(\d+) -> (\d+),(\d+)", "2,2 -> 2,1")

RegexMatch("2,2 -> 2,1", 1="2", 2="2", 3="2", 4="1")

In [97]:
[x for x in match(r"(\d+),(\d+) -> (\d+),(\d+)", "2,2 -> 2,1")]

4-element Vector{SubString{String}}:
 "2"
 "2"
 "2"
 "1"

In [105]:
parse.(Int64, [x for x in match(r"(\d+),(\d+) -> (\d+),(\d+)", "2,2 -> 2,1")])

4-element Vector{Int64}:
 2
 2
 2
 1

In [69]:
Int.(collect(Iterators.flatten((('1', '2'), ('3', '4')))))

4-element Vector{Int64}:
 49
 50
 51
 52

In [94]:
aa = collect(Iterators.flatten((('1', '2'), ('3', '4'))))

4-element Vector{Char}:
 '1': ASCII/Unicode U+0031 (category Nd: Number, decimal digit)
 '2': ASCII/Unicode U+0032 (category Nd: Number, decimal digit)
 '3': ASCII/Unicode U+0033 (category Nd: Number, decimal digit)
 '4': ASCII/Unicode U+0034 (category Nd: Number, decimal digit)

In [95]:
parse.(aa)

LoadError: MethodError: no method matching parse(::Char)
Closest candidates are:
  parse(::Type{T}, ::AbstractChar; base) where T<:Integer at /opt/julia-1.7.0/share/julia/base/parse.jl:40
  parse(::Type{T}, ::AbstractString; base) where T<:Integer at /opt/julia-1.7.0/share/julia/base/parse.jl:240
  parse(::Type{T}, ::AbstractString) where T<:Complex at /opt/julia-1.7.0/share/julia/base/parse.jl:381
  ...

In [68]:
map(((x1, y1), (x2, y2)) -> x, match(r"(\d+,\d+) -> (\d+,\d+)", "2,2 -> 2,1"))

LoadError: MethodError: no method matching (::var"#51#52")(::SubString{String})
Closest candidates are:
  (::var"#51#52")(::Any, ::Any) at In[68]:1

In [3]:
data = "2,5,5,3,2,2,5,1,4,5,2,1,5,5,1,2,3,3,4,1,4,1,4,4,2,1,5,5,3,5,4,3,4,1,5,4,1,5,5,5,4,3,1,2,1,5,1,4,4,1,4,1,3,1,1,1,3,1,1,2,1,3,1,1,1,2,3,5,5,3,2,3,3,2,2,1,3,1,3,1,5,5,1,2,3,2,1,1,2,1,2,1,2,2,1,3,5,4,3,3,2,2,3,1,4,2,2,1,3,4,5,4,2,5,4,1,2,1,3,5,3,3,5,4,1,1,5,2,4,4,1,2,2,5,5,3,1,2,4,3,3,1,4,2,5,1,5,1,2,1,1,1,1,3,5,5,1,5,5,1,2,2,1,2,1,2,1,2,1,4,5,1,2,4,3,3,3,1,5,3,2,2,1,4,2,4,2,3,2,5,1,5,1,1,1,3,1,1,3,5,4,2,5,3,2,2,1,4,5,1,3,2,5,1,2,1,4,1,5,5,1,2,2,1,2,4,5,3,3,1,4,4,3,1,4,2,4,4,3,4,1,4,5,3,1,4,2,2,3,4,4,4,1,4,3,1,3,4,5,1,5,4,4,4,5,5,5,2,1,3,4,3,2,5,3,1,3,2,2,3,1,4,5,3,5,5,3,2,3,1,2,5,2,1,3,1,1,1,5,1"

"2,5,5,3,2,2,5,1,4,5,2,1,5,5,1,2,3,3,4,1,4,1,4,4,2,1,5,5,3,5,4,3,4,1,5,4,1,5,5,5,4,3,1,2,1,5,1,4,4,1,4,1,3,1,1,1,3,1,1,2,1,3,1,1,1,2,3,5,5,3,2,3,3,2,2,1,3,1,3,1,5,5,1,2,3,2,1,1,2,1,2,1,2,2,1,3,5,4,3,3,2,2,3,1,4,2,2,1,3,4,5,4,2,5,4,1,2,1,3,5,3,3,5,4,1,1,5,2,4,4,1,2,2,5,5,3" ⋯ 57 bytes ⋯ "1,2,1,2,1,4,5,1,2,4,3,3,3,1,5,3,2,2,1,4,2,4,2,3,2,5,1,5,1,1,1,3,1,1,3,5,4,2,5,3,2,2,1,4,5,1,3,2,5,1,2,1,4,1,5,5,1,2,2,1,2,4,5,3,3,1,4,4,3,1,4,2,4,4,3,4,1,4,5,3,1,4,2,2,3,4,4,4,1,4,3,1,3,4,5,1,5,4,4,4,5,5,5,2,1,3,4,3,2,5,3,1,3,2,2,3,1,4,5,3,5,5,3,2,3,1,2,5,2,1,3,1,1,1,5,1"

In [21]:
data = "3,4,3,1,2"

"3,4,3,1,2"

In [29]:

fishes = parse.(Int64, split(data, ','))
for i in 0:18
    append!(fishes, fill(8, count(==(0), fishes)))
    fishes[fishes.==0] .= 9
    fishes .-= 1
end
length(fishes)

24

In [17]:
function doit(number)
    fishes = parse.(Int64, split(data, ','))
    for i in 0:number
        c = count(==(0), fishes)
        fishes[fishes.==0] .= 7
        fishes .-= 1
        append!(fishes, fill(8, c))
    end
    length(fishes)
end
doit(15)

21

In [195]:
push!(fill(9, 4), fill(4, 4))

LoadError: MethodError: Cannot `convert` an object of type Vector{Int64} to an object of type Int64
Closest candidates are:
  convert(::Type{T}, ::Ptr) where T<:Integer at /opt/julia-1.7.0/share/julia/base/pointer.jl:23
  convert(::Type{T}, ::T) where T<:Number at /opt/julia-1.7.0/share/julia/base/number.jl:6
  convert(::Type{T}, ::Number) where T<:Number at /opt/julia-1.7.0/share/julia/base/number.jl:7
  ...

In [10]:
a = [1,2,4,8,10]
c = zip(a, a[2:end])

zip([1, 2, 4, 8, 10], [2, 4, 8, 10])

In [114]:
data = "2,5,5,3,2,2,5,1,4,5,2,1,5,5,1,2,3,3,4,1,4,1,4,4,2,1,5,5,3,5,4,3,4,1,5,4,1,5,5,5,4,3,1,2,1,5,1,4,4,1,4,1,3,1,1,1,3,1,1,2,1,3,1,1,1,2,3,5,5,3,2,3,3,2,2,1,3,1,3,1,5,5,1,2,3,2,1,1,2,1,2,1,2,2,1,3,5,4,3,3,2,2,3,1,4,2,2,1,3,4,5,4,2,5,4,1,2,1,3,5,3,3,5,4,1,1,5,2,4,4,1,2,2,5,5,3,1,2,4,3,3,1,4,2,5,1,5,1,2,1,1,1,1,3,5,5,1,5,5,1,2,2,1,2,1,2,1,2,1,4,5,1,2,4,3,3,3,1,5,3,2,2,1,4,2,4,2,3,2,5,1,5,1,1,1,3,1,1,3,5,4,2,5,3,2,2,1,4,5,1,3,2,5,1,2,1,4,1,5,5,1,2,2,1,2,4,5,3,3,1,4,4,3,1,4,2,4,4,3,4,1,4,5,3,1,4,2,2,3,4,4,4,1,4,3,1,3,4,5,1,5,4,4,4,5,5,5,2,1,3,4,3,2,5,3,1,3,2,2,3,1,4,5,3,5,5,3,2,3,1,2,5,2,1,3,1,1,1,5,1"

"2,5,5,3,2,2,5,1,4,5,2,1,5,5,1,2,3,3,4,1,4,1,4,4,2,1,5,5,3,5,4,3,4,1,5,4,1,5,5,5,4,3,1,2,1,5,1,4,4,1,4,1,3,1,1,1,3,1,1,2,1,3,1,1,1,2,3,5,5,3,2,3,3,2,2,1,3,1,3,1,5,5,1,2,3,2,1,1,2,1,2,1,2,2,1,3,5,4,3,3,2,2,3,1,4,2,2,1,3,4,5,4,2,5,4,1,2,1,3,5,3,3,5,4,1,1,5,2,4,4,1,2,2,5,5,3" ⋯ 57 bytes ⋯ "1,2,1,2,1,4,5,1,2,4,3,3,3,1,5,3,2,2,1,4,2,4,2,3,2,5,1,5,1,1,1,3,1,1,3,5,4,2,5,3,2,2,1,4,5,1,3,2,5,1,2,1,4,1,5,5,1,2,2,1,2,4,5,3,3,1,4,4,3,1,4,2,4,4,3,4,1,4,5,3,1,4,2,2,3,4,4,4,1,4,3,1,3,4,5,1,5,4,4,4,5,5,5,2,1,3,4,3,2,5,3,1,3,2,2,3,1,4,5,3,5,5,3,2,3,1,2,5,2,1,3,1,1,1,5,1"

In [115]:
fishes = parse.(Int64, split(data, ','))
m = Dict()
for i in 0:8
    m[i] = 0
end

for i = fishes
    m[i] += 1
end

for l in 0:256-1
    for (k, v) in pairs(copy(m))
        if k == 0
            m[0] -= 1*v
            m[6] += 1*v
            m[8] += 1*v
        else
            m[k] -= 1*v
            m[k-1] += 1*v
        end
    end
end
sum(values(m))

1601616884019

In [126]:
using Statistics

In [154]:
data = "16,1,2,0,4,2,7,1,2,14"
data = parse.(Int64, split(data, ','))
target = median(data)
least_fuel = typemax(Int64)
for i in 1:length(data)/2
    for tf in (target, target * -1)
        fc = n -> 0.5*n*(n+1)
        fuel = sum(map.(x -> fc(abs(x - tf)), data))
        if fuel < least_fuel
            least_fuel = fuel
        end
    end
    target += 1
end
least_fuel

168.0

9223372036854775807

In [149]:
(1 < _)

LoadError: syntax: all-underscore identifier used as rvalue